<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_infokatalon.com_to-top</name>
   <tag></tag>
   <elementGuidId>d537b2ba-6194-4e81-8b57-be6a98821478</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#to-top</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='to-top']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4e573a26-d105-46e8-a3a5-5c05e336e446</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>to-top</value>
      <webElementGuid>b8f9da68-3a08-43d3-85f4-a230549c0684</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#top</value>
      <webElementGuid>b03b62a9-1990-4c70-848b-71ae13c1de3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-dark btn-lg</value>
      <webElementGuid>7d819449-c4f3-41f7-89b4-9ed6aff1258c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;to-top&quot;)</value>
      <webElementGuid>1ad595e9-a3ac-4a3f-96ca-44b07d1e1cd3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='to-top']</value>
      <webElementGuid>9c9049a5-b028-4e98-9051-ff777f1f7d07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='info@katalon.com'])[1]/following::a[4]</value>
      <webElementGuid>b4a35f9b-8e19-4353-a5ff-0b1802f8918d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(678) 813-1KMS'])[1]/following::a[5]</value>
      <webElementGuid>bf4430c7-a955-4acf-aaf2-458b1e5500d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#top')]</value>
      <webElementGuid>ba5848a3-5a1a-4e12-a4c8-0d7991ea0860</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//footer/a</value>
      <webElementGuid>96864737-d0b3-40ea-998d-f2709ca3c5aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'to-top' and @href = '#top']</value>
      <webElementGuid>a9e9f539-df2e-4ae7-b031-cdca8d9b197f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
